### ISSUE TITLE
猛男生存中的几个小特性

### ISSUE THREAD

**Issue by LittleHed** [EinsteinZheng/BraveSurvival#2]
*女巫会在地狱堡垒生成
*苦力怕会隔墙爆炸(一格)
*圆石和黑石被挖是百分百掉落且不会产生蠹虫的
*下界金矿石挖了也有几率不掉落，所有矿物使用精准采集即可百分百掉落且不生成蠹虫
*每次雷暴最多只会持续30秒
*使用末影珍珠必定会生成末影瞒
*僵尸和小白会捡起玩家的装备的武器
*食用所有肉类都会获得中毒+饥饿效果（腐肉不会）
目前bug:
身上拿着岩浆桶的时候，会在半砖、炼药锅着火(猛男生成只会在普通方块着火，在半砖上不会生成火焰及自身着火)
着火时站在灵魂沙上面，灵魂沙会直接消失
***装了猛男生存mod后，农作物还有木头什么的都不会生长了是什么鬼。。草方块都不蔓延了

**Comment by MCMocoder** [comment]
农作物不生长是tickChunk函数的小bug,我马上修改

**Comment by MCMocoder** [comment]
那个函数不小心覆盖了随机刻

**Comment by LittleHed** [comment]
好的

**Comment by MCMocoder** [comment]
明天早上更新新版本

**Comment by LittleHed** [comment]
话说能改一下火的特性么，在半砖、炼药锅等上是不会着火的，玩家自身着火是由火焰引燃的
而且不知道为什么，有时候会莫名奇妙着火，旁边没岩浆的
具体上面也有说

**Comment by MCMocoder** [comment]
新版本已经更改

**Comment by MCMocoder** [comment]
没有岩浆是因为岩浆被方块挡住

**Comment by LittleHed** [comment]
奥..

**Comment by MCMocoder** [comment]
tickChunk函数的bug修改正在测试

**Comment by MCMocoder** [comment]
已修复

**Comment by LittleHed** [comment]
好的，那其他特性能加一下么w，就上面说的那些ww
