### ISSUE TITLE
还有几个特性= =

### ISSUE THREAD

**Issue by LittleHed** [EinsteinZheng/BraveSurvival#3]
请求添加：
*女巫会在地狱堡垒生成
*苦力怕会隔墙爆炸(一格)
***圆石和黑石被挖是百分百掉落且不会产生蠹虫的
*下界金矿石挖了也有几率不掉落，所有矿物使用精准采集即可百分百掉落且不生成蠹虫
***每次雷暴最多只会持续30秒
*使用末影珍珠必定会生成末影瞒
*食用所有肉类都会获得中毒+饥饿效果（腐肉不会）
bug:
小白的伤害太高了，穿着金套都会被秒
现在在半砖和炼药锅上面还是会着火。。

**Comment by MCMocoder** [comment]
好的

**Comment by LittleHed** [comment]
w 感谢作者大大

**Comment by LittleHed** [comment]
啊对了，如果着火的时候站在灵魂沙上，灵魂沙会直接被替换成火-w-

**Comment by MCMocoder** [comment]
实测没有这个特性，建议下载最新版本

**Comment by MCMocoder** [comment]
新版雷暴是30-45s

**Comment by LittleHed** [comment]
我用的是1.6.0，这个bug确实有..

**Comment by LittleHed** [comment]
拿着岩浆桶站灵魂沙上，灵魂沙直接没了

**Comment by MCMocoder** [comment]
???我自己测试没有啊

**Comment by LittleHed** [comment]
啊这。。我用的是1.16.2服务器测试的

**Comment by MCMocoder** [comment]
我也是1.16.2啊

**Comment by LittleHed** [comment]
..我下的lastest releases，连雷暴也是超过了45秒
https://github.com/EinsteinZheng/BraveSurvival/releases/tag/1.6.0

**Comment by MCMocoder** [comment]
900ticks最长

**Comment by MCMocoder** [comment]
确认是特性，正在修复

**Comment by LittleHed** [comment]
对了，怪物掉装备的几率也降一下呗，我现在靠雷雨已经快集齐钻套和下界合金套了233333
*饱食度剩下一半的时候，会获得虚弱和缓慢效果，而且蘑菇牛应该也会变兔子

**Comment by MCMocoder** [comment]
天气系统已经修复，怪物掉装备的几率不用降，这样反倒平衡一些了

**Comment by MCMocoder** [comment]
版本号1.7.0

**Comment by LittleHed** [comment]
那其他的加了嘛= =

**Comment by MCMocoder** [comment]
暂时没有:(

**Comment by LittleHed** [comment]
az..那在半砖和炼药锅上面会着火的bug啥时候修emm
而且圆石和黑石的掉率是百分百的- -，这个应该可以直接改吧

**Comment by MCMocoder** [comment]
过几天会慢慢加，现在在魔改IntelliJ IDEA，把它变成C++ IDE，所以这里的维护工作可能会慢些

**Comment by LittleHed** [comment]
好的~
